import {
  AlertTriangle,
  Building2,
  CalendarDays,
  CalendarClock,
  FileSearch,
  UserCog,
  ClipboardList,
  House,
  PlugZap,
  RefreshCw,
  Settings2,
  ShieldCheck,
  Shirt,
  Trophy,
  Users,
  type LucideIcon,
} from "lucide-react";
import type { NavIcon } from "./nav";

export const NAV_ICONS: Record<NavIcon, LucideIcon> = {
  home: House,
  matches: CalendarDays,
  results: Trophy,
  players: Users,
  tables: ClipboardList,
  integrations: PlugZap,
  teams: Shirt,
  sync: RefreshCw,
  issues: AlertTriangle,
  derogations: CalendarClock,
  fbi: FileSearch,
  members: UserCog,
  settings: Settings2,
  platform: ShieldCheck,
  clubs: Building2,
};
